# Generated by Django 6.0.3 on 2026-03-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bg_color',
            field=models.CharField(default=12, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='icon_color',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
    ]
