# Generated by Django 6.0.3 on 2026-03-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_category_bg_color_category_icon_category_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='locale',
            field=models.CharField(default='fil_PH', max_length=20),
            preserve_default=False,
        ),
    ]
