# Generated by Django 6.0.3 on 2026-03-25 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpreferences'),
        ('transactions', '0003_currency_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_currency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_by', to='transactions.currency'),
            preserve_default=False,
        ),
    ]
